### ISSUE TITLE
End-grass biome generating in overworld!

### ISSUE THREAD

**Issue by Tokeli** [drizzs/GrassWorld-1.14#2]
Version: 1.1.4

When playing with the FTB Unstable 1.14 pack, I discovered that Light Grey End Grass biomes are generating in the overworld, using Biomes O Plenty. Some moderate exploring didn't show any other types.

**Comment by drizzs** [comment]
Yeah totally, its not using Biomes O Plenty, but i know what you mean.

Idk how it happened to be fair i didnt think it was doing this. I was watching an unstable stream so i could see my mod (yeah i'm vain) and i noticed the biome almost instantly and said damn that shouldn't be there.

Suffice to say in the new update this is not an issue. the new update does not make biomes at all so it will solve this problem. Any biomes still in the world will stay. Why only the grey one spawns and not the other one, i have no idea.

In the new update people have expressed(yes multiple) that they like the end grass biome because it spawns end slimes in the overworld. So what i did is added floating islands in 3 times nether overworld and end. each of which with different grasses that have different functionality. The end grass will spawn an extra rate of enderman and ender slimes, and the nether grass will spawn ghasts in the overworld. The update will be released in about a week or so.

This new update is a full overhaul not only will it solve this issue but it'll also make the mod MUCH smaller in size.

Thanks for posting this issue!

Drizzs

**Comment by Tokeli** [comment]
Sweet! Hopefully the new grass islands will have config options? It's kind of OP to get end-stone so easily in the overworld. And lord knows floating islands can get annoying with how many there are just from looking at Tinker's Construct.

Thanks!

**Comment by drizzs** [comment]
Configs for everything!
