### ISSUE TITLE
Add Minecraft Tags to Grass Blocks, Also Snowy Grass Textures

### ISSUE THREAD

**Issue by WenXin20** [drizzs/GrassWorld-1.14#4]
`Mineceaft v1.14.4`
`Forge v28.1.104`
`Grass World v2.0.0`

Grass Blocks are missing several minecraft block tags, which could prevent compatiblity with mods or even vanilla, such as being able to plant bamboo on colored grass.

Missing block tags:
`#minecraft:enderman_holdable`
`#minecraft:valid_spawn`
`#minecraft:bamboo_plantable_on`
`#minecraft:dirt_like`

Also, will snowy grass textures be added?

**Comment by drizzs** [comment]
I will add these in the next update

and yes there will be snowy grass textures. The thing about the textures is i plan on redoing how the colour is handled to a greyscale pixel system where i can control each instance of grey to a different colour on a scale palet i custom make so that my grass is not only unique but its only a few textures to save space as well as make it easier to add more grasses. I want to add coloured snowy grass textures, and instead of having snow form on top of the grass have the grass change to a texture that looks amost like its coloured under the snow, if that makes sense?

**Comment by WenXin20** [comment]
Nice!

**Comment by drizzs** [comment]
Done, except snowy textures! Added in next update! I'll make a new issue for the snowy textures!

**Comment by WenXin20** [comment]
I just realized that Colored Grass Blocks are probably also missing their item tags as well, which is separate from block tags.

And Netherrack, End Stone, Tall Grass, Logs, Leaves, & planks are also missing their corresponding block and item tags.
